MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "checkpoints/BDD100K/model_final.pth" 
  BACKBONE:
    CONV_BODY: "R-101-FPN" 
  RESNETS:
    BACKBONE_OUT_CHANNELS: 256
  RPN:
    USE_FPN: True
    ANCHOR_STRIDE: (4, 8, 16, 32, 64)
    PRE_NMS_TOP_N_TRAIN: 2000
    PRE_NMS_TOP_N_TEST: 1000
    POST_NMS_TOP_N_TEST: 1000
    FPN_POST_NMS_TOP_N_TEST: 1000
  ROI_HEADS:
    USE_FPN: True
    SCORE_THRESH: 0.5 # for running detection to collected boxes, for eval, should be 0.05
    NMS: 0.65
  ROI_BOX_HEAD:
    POOLER_RESOLUTION: 7
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    POOLER_SAMPLING_RATIO: 2
    FEATURE_EXTRACTOR: "FPN2MLPFeatureExtractor"
    PREDICTOR: "FPNPredictor"
    NUM_CLASSES: 11
  ROI_MASK_HEAD:
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    FEATURE_EXTRACTOR: "MaskRCNNFPNFeatureExtractor"
    PREDICTOR: "MaskRCNNC4Predictor"
    POOLER_RESOLUTION: 14
    POOLER_SAMPLING_RATIO: 2
    RESOLUTION: 28
    SHARE_BOX_FEATURE_EXTRACTOR: False
  MASK_ON: False
DATASETS:
  ROOT: 'data/BDD100K_plus_DoTA' 
  TRAIN: ("bdd100k_det_train_cocostyle",)
  TEST: ("bdd100k_dota",)
  CONVERT: False #True
DATALOADER:
  SIZE_DIVISIBILITY: 32
  NUM_WORKERS: 12
  ASPECT_RATIO_GROUPING: False
SOLVER:
  IMS_PER_BATCH: 6
  BASE_LR: 0.0075 #0.02
  WEIGHT_DECAY: 0.0001
  STEPS: (60000, 80000)
  MAX_ITER: 100000
TEST:
  IMS_PER_BATCH: 12 #84 #36
INPUT:
  MIN_SIZE_TEST: 720
  MAX_SIZE_TEST: 1280
OUTPUT_DIR: 'data/BDD100K_plus_DoTA/detection' 
